(cl:defpackage rbt_baxter_msgs-srv
  (:use )
  (:export
   "LISTCAMERAS"
   "<LISTCAMERAS-REQUEST>"
   "LISTCAMERAS-REQUEST"
   "<LISTCAMERAS-RESPONSE>"
   "LISTCAMERAS-RESPONSE"
   "OPENCAMERA"
   "<OPENCAMERA-REQUEST>"
   "OPENCAMERA-REQUEST"
   "<OPENCAMERA-RESPONSE>"
   "OPENCAMERA-RESPONSE"
   "SOLVEPOSITIONIK"
   "<SOLVEPOSITIONIK-REQUEST>"
   "SOLVEPOSITIONIK-REQUEST"
   "<SOLVEPOSITIONIK-RESPONSE>"
   "SOLVEPOSITIONIK-RESPONSE"
   "CLOSECAMERA"
   "<CLOSECAMERA-REQUEST>"
   "CLOSECAMERA-REQUEST"
   "<CLOSECAMERA-RESPONSE>"
   "CLOSECAMERA-RESPONSE"
  ))

