controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_right_arm_controller
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_both_arms_controller
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_left_hand_controller
    joints:
      []
  - name: fake_right_hand_controller
    joints:
      []