// Generated by gencpp from file bot_gazebo/ImageStateRequest.msg
// DO NOT EDIT!


#ifndef BOT_GAZEBO_MESSAGE_IMAGESTATEREQUEST_H
#define BOT_GAZEBO_MESSAGE_IMAGESTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_gazebo
{
template <class ContainerAllocator>
struct ImageStateRequest_
{
  typedef ImageStateRequest_<ContainerAllocator> Type;

  ImageStateRequest_()
    {
    }
  ImageStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageStateRequest_

typedef ::bot_gazebo::ImageStateRequest_<std::allocator<void> > ImageStateRequest;

typedef boost::shared_ptr< ::bot_gazebo::ImageStateRequest > ImageStateRequestPtr;
typedef boost::shared_ptr< ::bot_gazebo::ImageStateRequest const> ImageStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_gazebo::ImageStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bot_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::bot_gazebo::ImageStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_gazebo/ImageStateRequest";
  }

  static const char* value(const ::bot_gazebo::ImageStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::bot_gazebo::ImageStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_gazebo::ImageStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::bot_gazebo::ImageStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BOT_GAZEBO_MESSAGE_IMAGESTATEREQUEST_H
