// Generated by gencpp from file bot_gazebo/ImageState.msg
// DO NOT EDIT!


#ifndef BOT_GAZEBO_MESSAGE_IMAGESTATE_H
#define BOT_GAZEBO_MESSAGE_IMAGESTATE_H

#include <ros/service_traits.h>


#include <bot_gazebo/ImageStateRequest.h>
#include <bot_gazebo/ImageStateResponse.h>


namespace bot_gazebo
{

struct ImageState
{

typedef ImageStateRequest Request;
typedef ImageStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageState
} // namespace bot_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bot_gazebo::ImageState > {
  static const char* value()
  {
    return "5f88d2cd856d6dd2a610e6e9d5601882";
  }

  static const char* value(const ::bot_gazebo::ImageState&) { return value(); }
};

template<>
struct DataType< ::bot_gazebo::ImageState > {
  static const char* value()
  {
    return "bot_gazebo/ImageState";
  }

  static const char* value(const ::bot_gazebo::ImageState&) { return value(); }
};


// service_traits::MD5Sum< ::bot_gazebo::ImageStateRequest> should match 
// service_traits::MD5Sum< ::bot_gazebo::ImageState > 
template<>
struct MD5Sum< ::bot_gazebo::ImageStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bot_gazebo::ImageState >::value();
  }
  static const char* value(const ::bot_gazebo::ImageStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bot_gazebo::ImageStateRequest> should match 
// service_traits::DataType< ::bot_gazebo::ImageState > 
template<>
struct DataType< ::bot_gazebo::ImageStateRequest>
{
  static const char* value()
  {
    return DataType< ::bot_gazebo::ImageState >::value();
  }
  static const char* value(const ::bot_gazebo::ImageStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bot_gazebo::ImageStateResponse> should match 
// service_traits::MD5Sum< ::bot_gazebo::ImageState > 
template<>
struct MD5Sum< ::bot_gazebo::ImageStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bot_gazebo::ImageState >::value();
  }
  static const char* value(const ::bot_gazebo::ImageStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bot_gazebo::ImageStateResponse> should match 
// service_traits::DataType< ::bot_gazebo::ImageState > 
template<>
struct DataType< ::bot_gazebo::ImageStateResponse>
{
  static const char* value()
  {
    return DataType< ::bot_gazebo::ImageState >::value();
  }
  static const char* value(const ::bot_gazebo::ImageStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOT_GAZEBO_MESSAGE_IMAGESTATE_H
