// Generated by gencpp from file bot_gazebo/ImageStateResponse.msg
// DO NOT EDIT!


#ifndef BOT_GAZEBO_MESSAGE_IMAGESTATERESPONSE_H
#define BOT_GAZEBO_MESSAGE_IMAGESTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_gazebo
{
template <class ContainerAllocator>
struct ImageStateResponse_
{
  typedef ImageStateResponse_<ContainerAllocator> Type;

  ImageStateResponse_()
    : saved()  {
    }
  ImageStateResponse_(const ContainerAllocator& _alloc)
    : saved(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _saved_type;
  _saved_type saved;




  typedef boost::shared_ptr< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImageStateResponse_

typedef ::bot_gazebo::ImageStateResponse_<std::allocator<void> > ImageStateResponse;

typedef boost::shared_ptr< ::bot_gazebo::ImageStateResponse > ImageStateResponsePtr;
typedef boost::shared_ptr< ::bot_gazebo::ImageStateResponse const> ImageStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_gazebo::ImageStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bot_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f88d2cd856d6dd2a610e6e9d5601882";
  }

  static const char* value(const ::bot_gazebo::ImageStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f88d2cd856d6dd2ULL;
  static const uint64_t static_value2 = 0xa610e6e9d5601882ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_gazebo/ImageStateResponse";
  }

  static const char* value(const ::bot_gazebo::ImageStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string saved\n\
";
  }

  static const char* value(const ::bot_gazebo::ImageStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.saved);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_gazebo::ImageStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_gazebo::ImageStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "saved: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.saved);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_GAZEBO_MESSAGE_IMAGESTATERESPONSE_H
