// Generated by gencpp from file rbt_baxter_msgs/CloseCamera.msg
// DO NOT EDIT!


#ifndef RBT_BAXTER_MSGS_MESSAGE_CLOSECAMERA_H
#define RBT_BAXTER_MSGS_MESSAGE_CLOSECAMERA_H

#include <ros/service_traits.h>


#include <rbt_baxter_msgs/CloseCameraRequest.h>
#include <rbt_baxter_msgs/CloseCameraResponse.h>


namespace rbt_baxter_msgs
{

struct CloseCamera
{

typedef CloseCameraRequest Request;
typedef CloseCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseCamera
} // namespace rbt_baxter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbt_baxter_msgs::CloseCamera > {
  static const char* value()
  {
    return "1067b4a7f008fe1ff4bd9668312773fd";
  }

  static const char* value(const ::rbt_baxter_msgs::CloseCamera&) { return value(); }
};

template<>
struct DataType< ::rbt_baxter_msgs::CloseCamera > {
  static const char* value()
  {
    return "rbt_baxter_msgs/CloseCamera";
  }

  static const char* value(const ::rbt_baxter_msgs::CloseCamera&) { return value(); }
};


// service_traits::MD5Sum< ::rbt_baxter_msgs::CloseCameraRequest> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::CloseCamera > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::CloseCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::CloseCamera >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::CloseCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::CloseCameraRequest> should match 
// service_traits::DataType< ::rbt_baxter_msgs::CloseCamera > 
template<>
struct DataType< ::rbt_baxter_msgs::CloseCameraRequest>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::CloseCamera >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::CloseCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbt_baxter_msgs::CloseCameraResponse> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::CloseCamera > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::CloseCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::CloseCamera >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::CloseCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::CloseCameraResponse> should match 
// service_traits::DataType< ::rbt_baxter_msgs::CloseCamera > 
template<>
struct DataType< ::rbt_baxter_msgs::CloseCameraResponse>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::CloseCamera >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::CloseCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBT_BAXTER_MSGS_MESSAGE_CLOSECAMERA_H
