// Generated by gencpp from file rbt_baxter_msgs/ListCameras.msg
// DO NOT EDIT!


#ifndef RBT_BAXTER_MSGS_MESSAGE_LISTCAMERAS_H
#define RBT_BAXTER_MSGS_MESSAGE_LISTCAMERAS_H

#include <ros/service_traits.h>


#include <rbt_baxter_msgs/ListCamerasRequest.h>
#include <rbt_baxter_msgs/ListCamerasResponse.h>


namespace rbt_baxter_msgs
{

struct ListCameras
{

typedef ListCamerasRequest Request;
typedef ListCamerasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListCameras
} // namespace rbt_baxter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbt_baxter_msgs::ListCameras > {
  static const char* value()
  {
    return "855b31192ab61744e7deb992d94db7ff";
  }

  static const char* value(const ::rbt_baxter_msgs::ListCameras&) { return value(); }
};

template<>
struct DataType< ::rbt_baxter_msgs::ListCameras > {
  static const char* value()
  {
    return "rbt_baxter_msgs/ListCameras";
  }

  static const char* value(const ::rbt_baxter_msgs::ListCameras&) { return value(); }
};


// service_traits::MD5Sum< ::rbt_baxter_msgs::ListCamerasRequest> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::ListCameras > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::ListCamerasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::ListCameras >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::ListCamerasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::ListCamerasRequest> should match 
// service_traits::DataType< ::rbt_baxter_msgs::ListCameras > 
template<>
struct DataType< ::rbt_baxter_msgs::ListCamerasRequest>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::ListCameras >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::ListCamerasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbt_baxter_msgs::ListCamerasResponse> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::ListCameras > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::ListCamerasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::ListCameras >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::ListCamerasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::ListCamerasResponse> should match 
// service_traits::DataType< ::rbt_baxter_msgs::ListCameras > 
template<>
struct DataType< ::rbt_baxter_msgs::ListCamerasResponse>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::ListCameras >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::ListCamerasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBT_BAXTER_MSGS_MESSAGE_LISTCAMERAS_H
