// Generated by gencpp from file rbt_baxter_msgs/SolvePositionIK.msg
// DO NOT EDIT!


#ifndef RBT_BAXTER_MSGS_MESSAGE_SOLVEPOSITIONIK_H
#define RBT_BAXTER_MSGS_MESSAGE_SOLVEPOSITIONIK_H

#include <ros/service_traits.h>


#include <rbt_baxter_msgs/SolvePositionIKRequest.h>
#include <rbt_baxter_msgs/SolvePositionIKResponse.h>


namespace rbt_baxter_msgs
{

struct SolvePositionIK
{

typedef SolvePositionIKRequest Request;
typedef SolvePositionIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolvePositionIK
} // namespace rbt_baxter_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbt_baxter_msgs::SolvePositionIK > {
  static const char* value()
  {
    return "18cc92fd96853eb10b34de0b5c7d3cba";
  }

  static const char* value(const ::rbt_baxter_msgs::SolvePositionIK&) { return value(); }
};

template<>
struct DataType< ::rbt_baxter_msgs::SolvePositionIK > {
  static const char* value()
  {
    return "rbt_baxter_msgs/SolvePositionIK";
  }

  static const char* value(const ::rbt_baxter_msgs::SolvePositionIK&) { return value(); }
};


// service_traits::MD5Sum< ::rbt_baxter_msgs::SolvePositionIKRequest> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::SolvePositionIK > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::SolvePositionIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::SolvePositionIKRequest> should match 
// service_traits::DataType< ::rbt_baxter_msgs::SolvePositionIK > 
template<>
struct DataType< ::rbt_baxter_msgs::SolvePositionIKRequest>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::SolvePositionIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbt_baxter_msgs::SolvePositionIKResponse> should match 
// service_traits::MD5Sum< ::rbt_baxter_msgs::SolvePositionIK > 
template<>
struct MD5Sum< ::rbt_baxter_msgs::SolvePositionIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbt_baxter_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::SolvePositionIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbt_baxter_msgs::SolvePositionIKResponse> should match 
// service_traits::DataType< ::rbt_baxter_msgs::SolvePositionIK > 
template<>
struct DataType< ::rbt_baxter_msgs::SolvePositionIKResponse>
{
  static const char* value()
  {
    return DataType< ::rbt_baxter_msgs::SolvePositionIK >::value();
  }
  static const char* value(const ::rbt_baxter_msgs::SolvePositionIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBT_BAXTER_MSGS_MESSAGE_SOLVEPOSITIONIK_H
